#!/usr/bin/env bash
# One-click from-scratch install of dsh web behind a path-prefix proxy.
# Idempotent: safe to re-run at any time.
#
# Assumes the repo checkout is already present (it lives on the shared disk and
# survives container switches); this script installs everything else:
#   - Node/pnpm prerequisites
#   - workspace dependencies (pnpm install) and the web build (tsc + tsdown + Vite)
#   - the cross-container ~/.dsh home (symlink into the gitignored repo .dsh/)
#   - the web profile deployment layer (optional; see deployment values below)
#
# DEPLOYMENT VALUES are read from the environment or from the optional
# gitignored file deploy/deploy.env (copy deploy.env.example):
#   DSH_TRUSTED_HOSTS      space-separated authorities the /api trust fence admits
#   DSH_WORKSPACE_DEFAULT  absolute path the workspace picker opens at
# When both are unset the profile layer is skipped and dsh defaults apply
# (loopback-only fence, picker at the host home). Do not hardcode deployment
# values in this file.
#
# Start the server afterwards with: deploy/start.sh   (or: pnpm dsh web)
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DSH_HOME_TARGET="${REPO_DIR}/.dsh"                    # shared-disk DSH home (gitignored)
PNPM_VERSION=11.7.0
NODE_MIN_MAJOR=22
NODE_MIN_MINOR=19

# ── deployment values (env or gitignored deploy/deploy.env) ────────────────
if [ -f "${REPO_DIR}/deploy/deploy.env" ]; then
  # shellcheck disable=SC1091
  . "${REPO_DIR}/deploy/deploy.env"
fi
DSH_TRUSTED_HOSTS="${DSH_TRUSTED_HOSTS:-}"
DSH_WORKSPACE_DEFAULT="${DSH_WORKSPACE_DEFAULT:-}"

# ── helpers ─────────────────────────────────────────────────────────────────
say() { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[install] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

check_node() {
  command -v node >/dev/null 2>&1 || die "node not found — install Node >= ${NODE_MIN_MAJOR}.${NODE_MIN_MINOR} (nvm recommended)"
  local ver major minor
  ver="$(node --version | sed 's/^v//')"
  major="${ver%%.*}"
  minor="${ver#*.}"
  minor="${minor%%.*}"
  if [ "$major" -lt "$NODE_MIN_MAJOR" ] || { [ "$major" -eq "$NODE_MIN_MAJOR" ] && [ "$minor" -lt "$NODE_MIN_MINOR" ]; }; then
    die "node $ver is too old; the harness needs >= ${NODE_MIN_MAJOR}.${NODE_MIN_MINOR}"
  fi
  say "node $ver ok"
}

ensure_pnpm() {
  command -v pnpm >/dev/null 2>&1 && { say "pnpm $(pnpm --version) present"; return 0; }
  say "installing pnpm@${PNPM_VERSION} (npm global)"
  npm install --global "pnpm@${PNPM_VERSION}" || die "pnpm install failed — is the npm registry reachable?"
  say "pnpm installed"
}

ensure_dsh_home() {
  # The home directory is per-container: keep ~/.dsh as a symlink into the
  # shared disk so profiles, sessions, and credentials survive container switches.
  local link="$HOME/.dsh"
  if [ -L "$link" ]; then
    if [ "$(readlink "$link")" = "$DSH_HOME_TARGET" ]; then return 0; fi
    say "repointing stale ~/.dsh symlink"
    rm "$link"
  elif [ -d "$link" ]; then
    say "merging container-local ~/.dsh into the shared home"
    mkdir -p "$DSH_HOME_TARGET"
    cp -a "$link/." "$DSH_HOME_TARGET/"
    rm -rf "$link"
  fi
  mkdir -p "$DSH_HOME_TARGET"
  ln -s "$DSH_HOME_TARGET" "$link"
  say "~/.dsh -> $DSH_HOME_TARGET"
}

ensure_profile_patch() {
  local patch="$DSH_HOME_TARGET/profiles/web/cordis.patch.yml"
  mkdir -p "$(dirname "$patch")"
  if [ -f "$patch" ]; then
    say "web profile patch already exists — leaving it"
    return 0
  fi
  if [ -z "$DSH_TRUSTED_HOSTS" ] && [ -z "$DSH_WORKSPACE_DEFAULT" ]; then
    say "no deployment values set (DSH_TRUSTED_HOSTS / DSH_WORKSPACE_DEFAULT) — skipping profile layer"
    return 0
  fi
  local hosts=""
  local h
  for h in $DSH_TRUSTED_HOSTS; do hosts="${hosts}'${h}', "; done
  hosts="${hosts%, }"
  {
    echo "# Web profile deployment layer (generated by deploy/install.sh — gitignored)."
    echo "# One-click: \`pnpm dsh web\` needs no flags; every deployment value lives here."
    if [ -n "$DSH_WORKSPACE_DEFAULT" ]; then
      echo "- id: directory-picker"
      echo "  config:"
      echo "    defaultPath: ${DSH_WORKSPACE_DEFAULT}"
    fi
    if [ -n "$hosts" ]; then
      echo "- id: connection"
      echo "  config:"
      echo "    trustedHosts: !!js ctx.webRuntime.trustedHosts.concat([${hosts}])"
      echo "    privilegedHosts: !!js ctx.webRuntime.explicitTrustedHosts.concat([${hosts}])"
    fi
  } > "$patch"
  say "wrote web profile patch from deployment values"
}

needs_build() {
  local dist_html="$REPO_DIR/apps/web/dist/index.html"
  [ -f "$dist_html" ] || return 0
  local newer
  newer="$(find "$REPO_DIR/packages" "$REPO_DIR/apps" -type f \
    \( -name '*.ts' -o -name '*.tsx' -o -name '*.yml' -o -name '*.html' \) \
    -newer "$dist_html" -print -quit 2>/dev/null || true)"
  [ -n "$newer" ]
}

main() {
  cd "$REPO_DIR"
  say "repo: $REPO_DIR"
  check_node
  ensure_pnpm
  ensure_dsh_home
  ensure_profile_patch
  say "installing workspace dependencies (pnpm install)"
  pnpm install || die "pnpm install failed"
  if needs_build; then
    say "building (tsc + tsdown + web frontend)"
    pnpm run build || die "build failed"
  else
    say "build artifacts are up to date — skipping build"
  fi
  say "install complete. Start the server with: deploy/start.sh"
}

main "$@"
